Sprint 10
Ruslan-Yusov/java-filmorate pull request #5
Opened 2023-07-16 00:25 UTC by Ruslan-Yusov

2023-07-17 07:02 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmLikesService.java
> +        userService.getUsers(idUser);
Для чего данный вызов?

2023-07-17 07:12 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmLikesService.java
> +    private FilmService filmService;
То что filmService является частью FilmLikesService не понятно зачем.  Сервис - это некоторая ограниченная бизнес контекстом логика. Сервис может зависеть от репозиториев/хранилищ т.е чего-то не содержащего бизнес логику. Иначе бизнес логика одного бизнес контекста будет размазываться по нескольким сервисам и это не есть хорошо.  Здесь лучше сделать зависимость от хранилищ а не от сервисов.

2023-07-17 07:19 UTC, VadimZharkov requested changes
Лучше внедрять зависимости через конструктор.
Бонусы ледущие:
1 объект не создасться без зависимостей. след. можно быть уверенным о его состоянии.
2 в тестах можно создать данный объект и передать в него моки зависимостей без необходимости наличия механизмов DI спринга. т.е. можно  тестировать где угодно в любых фреймворках.

2023-07-17 17:12 UTC, Ruslan-Yusov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmLikesService.java
> +        userService.getUsers(idUser);
Данный метод проверяет наличие юзера в данных, чем обеспечивает консистентность.

2023-07-17 17:20 UTC, Ruslan-Yusov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmLikesService.java
> +    private FilmService filmService;
Консистентность гарантируется и проверяется не репозиторием, а FilmService, UserService. В частности проверка наличия объекта инкапсулирована в 1 месте, а не размазана согласно KISS и SOLID.

2023-07-18 07:04 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmLikesService.java
> +        userService.getUsers(idUser);
Из названия метода не очевидно что здесь есть проверка юзера на наличие. Из названия очевидно что здесь получение пользователя, которого нигде далее не используется.

2023-07-18 07:20 UTC, VadimZharkov approved these changes

2023-07-18 08:11 UTC, merged